# Generated by Django 4.2 on 2023-05-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number1',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number2',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadin')], max_length=1),
        ),
    ]
